### ISSUE TITLE
postcss error

### ISSUE THREAD

**Issue by renardpal** [negrel/hugo-theme-pico#3]
trying to use your nice theme & example site but I get a postcss error. Any idea how to solve this?

```
Building sites … TypeError: Invalid PostCSS Plugin found at: plugins[2]
(@/Users/renardpal/Documents/GitHub/exampleSite/themes/pico/assets/config/postcss.config.js)
    at /Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/plugins.js:72:15
    at Array.forEach (<anonymous>)
    at plugins (/Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/plugins.js:58:13)
    at processResult (/Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/index.js:33:14)
    at /Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/index.js:94:14
    at async Promise.all (index 0)
TypeError: Invalid PostCSS Plugin found at: plugins[2]

(@/Users/renardpal/Documents/GitHub/exampleSite/themes/pico/assets/config/postcss.config.js)
    at /Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/plugins.js:72:15
    at Array.forEach (<anonymous>)
    at plugins (/Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/plugins.js:58:13)
    at processResult (/Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/index.js:33:14)
    at /Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/index.js:94:14
    at async Promise.all (index 0)
TypeError: Invalid PostCSS Plugin found at: plugins[2]

(@/Users/renardpal/Documents/GitHub/exampleSite/themes/pico/assets/config/postcss.config.js)
    at /Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/plugins.js:72:15
    at Array.forEach (<anonymous>)
    at plugins (/Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/plugins.js:58:13)
    at processResult (/Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/index.js:33:14)
    at /Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/index.js:94:14
    at async Promise.all (index 0)
ERROR 2020/09/16 11:44:40 POSTCSS: failed to transform "style/style.css" (text/css): TypeError: Invalid PostCSS Plugin found at: plugins[2]

(@/Users/renardpal/Documents/GitHub/exampleSite/themes/pico/assets/config/postcss.config.js)
    at /Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/plugins.js:72:15
    at Array.forEach (<anonymous>)
    at plugins (/Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/plugins.js:58:13)
    at processResult (/Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/index.js:33:14)
    at /Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/index.js:94:14
    at async Promise.all (index 0)
ERROR 2020/09/16 11:44:40 POSTCSS: failed to transform "css/main.css" (text/css): TypeError: Invalid PostCSS Plugin found at: plugins[2]

(@/Users/renardpal/Documents/GitHub/exampleSite/themes/pico/assets/config/postcss.config.js)
    at /Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/plugins.js:72:15
    at Array.forEach (<anonymous>)
    at plugins (/Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/plugins.js:58:13)
    at processResult (/Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/index.js:33:14)
    at /Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/index.js:94:14
    at async Promise.all (index 0)
Total in 2110 ms
Error: Error building site: POSTCSS: failed to transform "css/main.css" (text/css): TypeError: Invalid PostCSS Plugin found at: plugins[2]

(@/Users/renardpal/Documents/GitHub/exampleSite/themes/pico/assets/config/postcss.config.js)
    at /Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/plugins.js:72:15
    at Array.forEach (<anonymous>)
    at plugins (/Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/plugins.js:58:13)
    at processResult (/Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/index.js:33:14)
    at /Users/renardpal/Documents/GitHub/exampleSite/node_modules/postcss-load-config/src/index.js:94:14
    at async Promise.all (index 0)
(base) renardpal:exampleSite renardpal$ 
```

**Comment by negrel** [comment]
This is an error concerning the postcss plugin "autoprefixer". Version 10.0.0 was released yesterday and should be compatible later. 

I suggest you downgrade the "autoprefixer" plugin to version 9.8.6 with the following command:
```
npm install autoprefixer@9.8.6 
```

See https://github.com/postcss/autoprefixer/issues/1358 for more info
